version: '3'
services:
  # Express application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
      - JWT_SECRET=shrry
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  # PostgreSQL database service
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

# Volumes for persistent data storage
volumes:
  postgres-data:

# Network for connecting services
networks:
  app-network:
